In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB

# A- Phase d’apprentissage

In [2]:
df_train = pd.read_csv("processed.cleveland.data", header=None)
df_train = df_train[[0, 1, 2, 5, 6, 8, 13]]

## Edit columns name

In [3]:
df_train.columns = ["age", "sex", "cp", "fbs", "restecg", "exang", "num"]
df_train.head()

age  sex   cp  fbs  restecg  exang  num
0  63.0  1.0  1.0  1.0      2.0    0.0    0
1  67.0  1.0  4.0  0.0      2.0    1.0    2
2  67.0  1.0  4.0  0.0      2.0    1.0    1
3  37.0  1.0  3.0  0.0      0.0    0.0    0
4  41.0  0.0  2.0  0.0      2.0    0.0    0

## Attribut "num"

In [4]:
df_train.loc[df_train["num"] == 0, "num"] = 0
df_train.loc[df_train["num"] != 0, "num"] = 1

## Attribut "age"

In [5]:
df_train.loc[df_train["age"] < 50, "age"] = 0
df_train.loc[df_train["age"] >= 50, "age"] = 1

## Attribut "cp"

In [6]:
df_train["cp_1"] = df_train.loc[df_train["cp"] == 1, "cp"]
df_train["cp_2"] = df_train.loc[df_train["cp"] == 2, "cp"]
df_train["cp_3"] = df_train.loc[df_train["cp"] == 3, "cp"]
df_train["cp_4"] = df_train.loc[df_train["cp"] == 4, "cp"]

df_train.loc[~df_train['cp_1'].isnull(),'cp_1'] = 1
df_train.loc[df_train['cp_1'].isnull(),'cp_1'] = 0
df_train.loc[~df_train['cp_2'].isnull(),'cp_2'] = 1
df_train.loc[df_train['cp_2'].isnull(),'cp_2'] = 0
df_train.loc[~df_train['cp_3'].isnull(),'cp_3'] = 1
df_train.loc[df_train['cp_3'].isnull(),'cp_3'] = 0
df_train.loc[~df_train['cp_4'].isnull(),'cp_4'] = 1
df_train.loc[df_train['cp_4'].isnull(),'cp_4'] = 0

## Attribut "restecg"

In [7]:
df_train["restecg_0"] = df_train.loc[df_train["restecg"] == 0, "restecg"]
df_train["restecg_1"] = df_train.loc[df_train["restecg"] == 1, "restecg"]
df_train["restecg_2"] = df_train.loc[df_train["restecg"] == 2, "restecg"]

df_train.loc[~df_train['restecg_0'].isnull(),'restecg_0'] = 1
df_train.loc[df_train['restecg_0'].isnull(),'restecg_0'] = 0
df_train.loc[~df_train['restecg_1'].isnull(),'restecg_1'] = 1
df_train.loc[df_train['restecg_1'].isnull(),'restecg_1'] = 0
df_train.loc[~df_train['restecg_2'].isnull(),'restecg_2'] = 1
df_train.loc[df_train['restecg_2'].isnull(),'restecg_2'] = 0
df_train

age  sex   cp  fbs  restecg  exang  num  cp_1  cp_2  cp_3  cp_4  \
0    1.0  1.0  1.0  1.0      2.0    0.0    0   1.0   0.0   0.0   0.0   
1    1.0  1.0  4.0  0.0      2.0    1.0    1   0.0   0.0   0.0   1.0   
2    1.0  1.0  4.0  0.0      2.0    1.0    1   0.0   0.0   0.0   1.0   
3    0.0  1.0  3.0  0.0      0.0    0.0    0   0.0   0.0   1.0   0.0   
4    0.0  0.0  2.0  0.0      2.0    0.0    0   0.0   1.0   0.0   0.0   
..   ...  ...  ...  ...      ...    ...  ...   ...   ...   ...   ...   
298  0.0  1.0  1.0  0.0      0.0    0.0    1   1.0   0.0   0.0   0.0   
299  1.0  1.0  4.0  1.0      0.0    0.0    1   0.0   0.0   0.0   1.0   
300  1.0  1.0  4.0  0.0      0.0    1.0    1   0.0   0.0   0.0   1.0   
301  1.0  0.0  2.0  0.0      2.0    0.0    1   0.0   1.0   0.0   0.0   
302  0.0  1.0  3.0  0.0      0.0    0.0    0   0.0   0.0   1.0   0.0   

     restecg_0  restecg_1  restecg_2  
0          0.0        0.0        1.0  
1          0.0        0.0        1.0  
2          0.0        0.0        1.0  
3          1.0        0.0        0.0  
4          0.0        0.0        1.0  
..         ...        ...        ...  
298        1.0        0.0        0.0  
299        1.0        0.0        0.0  
300        1.0        0.0        0.0  
301        0.0        0.0        1.0  
302        1.0        0.0        0.0  

[303 rows x 14 columns]

In [8]:
gnb = BernoulliNB()
gnb.fit(df_train[["age", "sex", "cp", "fbs", "restecg", "exang", "cp_1", "cp_2", "cp_3", "cp_4", "restecg_0", "restecg_1", "restecg_2"]], df_train["num"])

BernoulliNB()

## 1- Calcul de Phi_y

In [9]:
gnb.class_log_prior_

array([-0.61386638, -0.77925887])

## 2- Calcul de Phi_k|Y=1

In [10]:
gnb.feature_log_prob_[1]

array([-0.21256144, -0.20382776, -0.00711747, -1.81326567, -0.51794309,
       -0.60495447, -2.86931835, -2.6461748 , -2.00432091, -0.2853208 ,
       -0.90570862, -3.56246553, -0.55431074])

## 3- Calcul de Phi_k|Y=0

In [11]:
gnb.feature_log_prob_[0]

array([-0.46759689, -0.5793883 , -0.00604231, -1.93393396, -0.86349255,
       -1.93393396, -2.27877444, -1.37431817, -0.87788128, -1.42310833,
       -0.5476396 , -4.41884061, -0.87788128])

# B- Phase de test et evaluation

In [12]:
df_test = pd.read_csv("reprocessed.hungarian.data", header=None)
df_test.columns = ["col"]
df_test = pd.DataFrame(df_test.col.str.split(' ').tolist(), columns = ["age", "sex", "cp", "fbs", "restecg", "exang", "cp_1", "cp_2", "cp_3", "cp_4", "restecg_0", "restecg_1", "restecg_2", "num"])
df_test["age"] = pd.to_numeric(df_test["age"], downcast="float")
df_test["sex"] = pd.to_numeric(df_test["sex"], downcast="float")
df_test["cp"] = pd.to_numeric(df_test["cp"], downcast="float")
df_test["fbs"] = pd.to_numeric(df_test["fbs"], downcast="float")
df_test["restecg"] = pd.to_numeric(df_test["restecg"], downcast="float")
df_test["exang"] = pd.to_numeric(df_test["exang"], downcast="float")
df_test["cp_1"] = pd.to_numeric(df_test["cp_1"], downcast="float")
df_test["cp_2"] = pd.to_numeric(df_test["cp_2"], downcast="float")
df_test["cp_3"] = pd.to_numeric(df_test["cp_3"], downcast="float")
df_test["cp_4"] = pd.to_numeric(df_test["cp_4"], downcast="float")
df_test["restecg_0"] = pd.to_numeric(df_test["restecg_0"], downcast="float")
df_test["restecg_1"] = pd.to_numeric(df_test["restecg_1"], downcast="float")
df_test["restecg_2"] = pd.to_numeric(df_test["restecg_2"], downcast="float")
df_test["num"] = pd.to_numeric(df_test["num"], downcast="float")
df_test.head()

age  sex   cp    fbs  restecg  exang  cp_1   cp_2  cp_3  cp_4  restecg_0  \
0  40.0  1.0  2.0  140.0    289.0    0.0   0.0  172.0   0.0   0.0       -9.0   
1  49.0  0.0  3.0  160.0    180.0    0.0   0.0  156.0   0.0   1.0        2.0   
2  37.0  1.0  2.0  130.0    283.0    0.0   1.0   98.0   0.0   0.0       -9.0   
3  48.0  0.0  4.0  138.0    214.0    0.0   0.0  108.0   1.0   1.5        2.0   
4  54.0  1.0  3.0  150.0     -9.0    0.0   0.0  122.0   0.0   0.0       -9.0   

   restecg_1  restecg_2  num  
0       -9.0       -9.0  0.0  
1       -9.0       -9.0  1.0  
2       -9.0       -9.0  0.0  
3       -9.0       -9.0  3.0  
4       -9.0       -9.0  0.0

## Attribut "num"

In [13]:
df_test.loc[df_test["num"] == 0, "num"] = 0
df_test.loc[df_test["num"] != 0, "num"] = 1

## Attribut "age"

In [14]:
df_test.loc[df_test["age"] < 50, "age"] = 0
df_test.loc[df_test["age"] >= 50, "age"] = 1

## Attribut "cp"

In [15]:
df_test["cp_1"] = df_test.loc[df_test["cp"] == 1, "cp"]
df_test["cp_2"] = df_test.loc[df_test["cp"] == 2, "cp"]
df_test["cp_3"] = df_test.loc[df_test["cp"] == 3, "cp"]
df_test["cp_4"] = df_test.loc[df_test["cp"] == 4, "cp"]

df_test.loc[~df_test['cp_1'].isnull(),'cp_1'] = 1
df_test.loc[df_test['cp_1'].isnull(),'cp_1'] = 0
df_test.loc[~df_test['cp_2'].isnull(),'cp_2'] = 1
df_test.loc[df_test['cp_2'].isnull(),'cp_2'] = 0
df_test.loc[~df_test['cp_3'].isnull(),'cp_3'] = 1
df_test.loc[df_test['cp_3'].isnull(),'cp_3'] = 0
df_test.loc[~df_test['cp_4'].isnull(),'cp_4'] = 1
df_test.loc[df_test['cp_4'].isnull(),'cp_4'] = 0

## Attribut "restecg"

In [16]:
df_test["restecg_0"] = df_test.loc[df_test["restecg"] == 0, "restecg"]
df_test["restecg_1"] = df_test.loc[df_test["restecg"] == 1, "restecg"]
df_test["restecg_2"] = df_test.loc[df_test["restecg"] == 2, "restecg"]

df_test.loc[~df_test['restecg_0'].isnull(),'restecg_0'] = 1
df_test.loc[df_test['restecg_0'].isnull(),'restecg_0'] = 0
df_test.loc[~df_test['restecg_1'].isnull(),'restecg_1'] = 1
df_test.loc[df_test['restecg_1'].isnull(),'restecg_1'] = 0
df_test.loc[~df_test['restecg_2'].isnull(),'restecg_2'] = 1
df_test.loc[df_test['restecg_2'].isnull(),'restecg_2'] = 0
df_test.head()

age  sex   cp    fbs  restecg  exang  cp_1  cp_2  cp_3  cp_4  restecg_0  \
0  0.0  1.0  2.0  140.0    289.0    0.0   0.0   1.0   0.0   0.0        0.0   
1  0.0  0.0  3.0  160.0    180.0    0.0   0.0   0.0   1.0   0.0        0.0   
2  0.0  1.0  2.0  130.0    283.0    0.0   0.0   1.0   0.0   0.0        0.0   
3  0.0  0.0  4.0  138.0    214.0    0.0   0.0   0.0   0.0   1.0        0.0   
4  1.0  1.0  3.0  150.0     -9.0    0.0   0.0   0.0   1.0   0.0        0.0   

   restecg_1  restecg_2  num  
0        0.0        0.0  0.0  
1        0.0        0.0  1.0  
2        0.0        0.0  0.0  
3        0.0        0.0  1.0  
4        0.0        0.0  0.0

## 1- Calcul de log(Phi_x|y=1) + log(P(y = 1))

In [17]:
res_1 = gnb.feature_log_prob_[1] + gnb.class_log_prior_[1].reshape(-1,1)

## 2- Calcul de log(Phi_x|y=0) + log(P(y = 0))

In [18]:
res_0 = gnb.feature_log_prob_[0] + gnb.class_log_prior_[0].reshape(-1,1)

## 3- Et conclure en comparant les deux dans chaque cas

In [19]:
res_1 > res_0

array([[ True,  True, False, False,  True,  True, False, False, False,
         True, False,  True,  True]])

Les "age", "sex", "restecg", "cp_1", "cp_4", "restecg_1", "restecg_2" influent beaucoup plus sur la maladie que les autres facteurs.

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(df_test['num'], gnb.predict(df_test[["age", "sex", "cp", "fbs", "restecg", "exang", "cp_1", "cp_2", "cp_3", "cp_4", "restecg_0", "restecg_1", "restecg_2"]]))

array([[100,  23],
       [ 16,  55]])

Taux de positifs bien classés

In [21]:
154/(154+24)

0.8651685393258427

Taux de negatifs mal classés

In [22]:
34/(34+82)

0.29310344827586204

# C- Ajustement de la taille de l’ensemble d’apprentissage

In [23]:
df_train = df_train.append(df_test[:100], sort=False)
df_train

age  sex   cp    fbs  restecg  exang  num  cp_1  cp_2  cp_3  cp_4  \
0   1.0  1.0  1.0    1.0      2.0    0.0  0.0   1.0   0.0   0.0   0.0   
1   1.0  1.0  4.0    0.0      2.0    1.0  1.0   0.0   0.0   0.0   1.0   
2   1.0  1.0  4.0    0.0      2.0    1.0  1.0   0.0   0.0   0.0   1.0   
3   0.0  1.0  3.0    0.0      0.0    0.0  0.0   0.0   0.0   1.0   0.0   
4   0.0  0.0  2.0    0.0      2.0    0.0  0.0   0.0   1.0   0.0   0.0   
..  ...  ...  ...    ...      ...    ...  ...   ...   ...   ...   ...   
95  1.0  1.0  4.0  130.0    263.0    0.0  1.0   0.0   0.0   0.0   1.0   
96  0.0  1.0  2.0  142.0    207.0    0.0  0.0   0.0   1.0   0.0   0.0   
97  0.0  1.0  3.0  160.0    147.0    1.0  0.0   0.0   0.0   1.0   0.0   
98  1.0  1.0  4.0  120.0     85.0    0.0  0.0   0.0   0.0   0.0   1.0   
99  0.0  1.0  2.0  125.0    269.0    0.0  0.0   0.0   1.0   0.0   0.0   

    restecg_0  restecg_1  restecg_2  
0         0.0        0.0        1.0  
1         0.0        0.0        1.0  
2         0.0        0.0        1.0  
3         1.0        0.0        0.0  
4         0.0        0.0        1.0  
..        ...        ...        ...  
95        0.0        0.0        0.0  
96        0.0        0.0        0.0  
97        0.0        0.0        0.0  
98        0.0        0.0        0.0  
99        0.0        0.0        0.0  

[403 rows x 14 columns]

In [25]:
from sklearn.metrics import confusion_matrix

df_test = df_test[100:]
gnb = BernoulliNB()
gnb.fit(df_train[["age", "sex", "cp", "fbs", "restecg", "exang", "cp_1", "cp_2", "cp_3", "cp_4", "restecg_0", "restecg_1", "restecg_2"]], df_train["num"])

BernoulliNB()

In [26]:
confusion_matrix(df_test['num'], gnb.predict(df_test[["age", "sex", "cp", "fbs", "restecg", "exang", "cp_1", "cp_2", "cp_3", "cp_4", "restecg_0", "restecg_1", "restecg_2"]]))

array([[100,  23],
       [ 16,  55]])

Taux de positifs bien classés

In [27]:
100/(100+16)

0.8620689655172413

Taux de negatifs mal classés

In [29]:
23/(23+55)

0.2948717948717949

Le resultat demontre que cela n'affecte pas de gros changement au niveau de la performance. Cela est due peut etre à une debalancement de classe (beaucoup plus de classe positif que de negatif). Ce qui entraine une forte precision du coté de la classe des positif.